//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIN.FacturacionServiciosBasicos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="SIN.FacturacionServiciosBasicos.ServicioFacturacion")]
    public interface ServicioFacturacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(SIN.FacturacionServiciosBasicos.recepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.verificarComunicacionResponse> verificarComunicacionAsync(SIN.FacturacionServiciosBasicos.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionFacturaResponse> recepcionFacturaAsync(SIN.FacturacionServiciosBasicos.recepcionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(SIN.FacturacionServiciosBasicos.validacionRecepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(SIN.FacturacionServiciosBasicos.recepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(SIN.FacturacionServiciosBasicos.verificacionEstadoFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(SIN.FacturacionServiciosBasicos.validacionRecepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.anulacionFacturaResponse> anulacionFacturaAsync(SIN.FacturacionServiciosBasicos.anulacionFactura request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionPaquete : solicitudRecepcionFactura
    {
        
        private string cafcField;
        
        private int cantidadFacturasField;
        
        private long codigoEventoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cafc
        {
            get
            {
                return this.cafcField;
            }
            set
            {
                this.cafcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadFacturas
        {
            get
            {
                return this.cantidadFacturasField;
            }
            set
            {
                this.cantidadFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long codigoEvento
        {
            get
            {
                return this.codigoEventoField;
            }
            set
            {
                this.codigoEventoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionFactura : solicitudRecepcion
    {
        
        private byte[] archivoField;
        
        private string fechaEnvioField;
        
        private string hashArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaEnvio
        {
            get
            {
                return this.fechaEnvioField;
            }
            set
            {
                this.fechaEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hashArchivo
        {
            get
            {
                return this.hashArchivoField;
            }
            set
            {
                this.hashArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcion : modelDto
    {
        
        private int codigoAmbienteField;
        
        private int codigoDocumentoSectorField;
        
        private int codigoEmisionField;
        
        private int codigoModalidadField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cufdField;
        
        private string cuisField;
        
        private long nitField;
        
        private int tipoFacturaDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoDocumentoSector
        {
            get
            {
                return this.codigoDocumentoSectorField;
            }
            set
            {
                this.codigoDocumentoSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoEmision
        {
            get
            {
                return this.codigoEmisionField;
            }
            set
            {
                this.codigoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string cufd
        {
            get
            {
                return this.cufdField;
            }
            set
            {
                this.cufdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int tipoFacturaDocumento
        {
            get
            {
                return this.tipoFacturaDocumentoField;
            }
            set
            {
                this.tipoFacturaDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeRecepcion : mensajeServicio
    {
        
        private bool advertenciaField;
        
        private bool advertenciaFieldSpecified;
        
        private int numeroArchivoField;
        
        private bool numeroArchivoFieldSpecified;
        
        private int numeroDetalleField;
        
        private bool numeroDetalleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool advertencia
        {
            get
            {
                return this.advertenciaField;
            }
            set
            {
                this.advertenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool advertenciaSpecified
        {
            get
            {
                return this.advertenciaFieldSpecified;
            }
            set
            {
                this.advertenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroArchivo
        {
            get
            {
                return this.numeroArchivoField;
            }
            set
            {
                this.numeroArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroArchivoSpecified
        {
            get
            {
                return this.numeroArchivoFieldSpecified;
            }
            set
            {
                this.numeroArchivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroDetalle
        {
            get
            {
                return this.numeroDetalleField;
            }
            set
            {
                this.numeroDetalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDetalleSpecified
        {
            get
            {
                return this.numeroDetalleFieldSpecified;
            }
            set
            {
                this.numeroDetalleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaRecepcion : modelDto
    {
        
        private string codigoDescripcionField;
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string codigoRecepcionField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDescripcion
        {
            get
            {
                return this.codigoDescripcionField;
            }
            set
            {
                this.codigoDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEstado
        {
            get
            {
                return this.codigoEstadoField;
            }
            set
            {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified
        {
            get
            {
                return this.codigoEstadoFieldSpecified;
            }
            set
            {
                this.codigoEstadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public mensajeRecepcion[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudAnulacion : solicitudRecepcion
    {
        
        private int codigoMotivoField;
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoMotivo
        {
            get
            {
                return this.codigoMotivoField;
            }
            set
            {
                this.codigoMotivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificacionEstado : solicitudRecepcion
    {
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudValidacionRecepcion : solicitudRecepcion
    {
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionMasiva : solicitudRecepcionFactura
    {
        
        private int cantidadFacturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadFacturas
        {
            get
            {
                return this.cantidadFacturasField;
            }
            set
            {
                this.cantidadFacturasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete;
        
        public recepcionPaqueteFactura()
        {
        }
        
        public recepcionPaqueteFactura(SIN.FacturacionServiciosBasicos.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete)
        {
            this.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionPaqueteFacturaResponse()
        {
        }
        
        public recepcionPaqueteFacturaResponse(SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion
    {
        
        public verificarComunicacion()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaComunicacion @return;
        
        public verificarComunicacionResponse()
        {
        }
        
        public verificarComunicacionResponse(SIN.FacturacionServiciosBasicos.respuestaComunicacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.solicitudRecepcionFactura SolicitudServicioRecepcionFactura;
        
        public recepcionFactura()
        {
        }
        
        public recepcionFactura(SIN.FacturacionServiciosBasicos.solicitudRecepcionFactura SolicitudServicioRecepcionFactura)
        {
            this.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionFacturaResponse()
        {
        }
        
        public recepcionFacturaResponse(SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva;
        
        public validacionRecepcionMasivaFactura()
        {
        }
        
        public validacionRecepcionMasivaFactura(SIN.FacturacionServiciosBasicos.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva)
        {
            this.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionMasivaFacturaResponse()
        {
        }
        
        public validacionRecepcionMasivaFacturaResponse(SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva;
        
        public recepcionMasivaFactura()
        {
        }
        
        public recepcionMasivaFactura(SIN.FacturacionServiciosBasicos.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva)
        {
            this.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionMasivaFacturaResponse()
        {
        }
        
        public recepcionMasivaFacturaResponse(SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura;
        
        public verificacionEstadoFactura()
        {
        }
        
        public verificacionEstadoFactura(SIN.FacturacionServiciosBasicos.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura)
        {
            this.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion;
        
        public verificacionEstadoFacturaResponse()
        {
        }
        
        public verificacionEstadoFacturaResponse(SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete;
        
        public validacionRecepcionPaqueteFactura()
        {
        }
        
        public validacionRecepcionPaqueteFactura(SIN.FacturacionServiciosBasicos.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete)
        {
            this.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionPaqueteFacturaResponse()
        {
        }
        
        public validacionRecepcionPaqueteFacturaResponse(SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.solicitudAnulacion SolicitudServicioAnulacionFactura;
        
        public anulacionFactura()
        {
        }
        
        public anulacionFactura(SIN.FacturacionServiciosBasicos.solicitudAnulacion SolicitudServicioAnulacionFactura)
        {
            this.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion;
        
        public anulacionFacturaResponse()
        {
        }
        
        public anulacionFacturaResponse(SIN.FacturacionServiciosBasicos.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal interface ServicioFacturacionChannel : SIN.FacturacionServiciosBasicos.ServicioFacturacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<SIN.FacturacionServiciosBasicos.ServicioFacturacion>, SIN.FacturacionServiciosBasicos.ServicioFacturacion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturacionClient() : 
                base(ServicioFacturacionClient.GetDefaultBinding(), ServicioFacturacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioFacturacionPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionPaqueteFacturaResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.recepcionPaqueteFacturaAsync(SIN.FacturacionServiciosBasicos.recepcionPaqueteFactura request)
        {
            return base.Channel.recepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(SIN.FacturacionServiciosBasicos.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete)
        {
            SIN.FacturacionServiciosBasicos.recepcionPaqueteFactura inValue = new SIN.FacturacionServiciosBasicos.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).recepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.verificarComunicacionResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.verificarComunicacionAsync(SIN.FacturacionServiciosBasicos.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.verificarComunicacionResponse> verificarComunicacionAsync()
        {
            SIN.FacturacionServiciosBasicos.verificarComunicacion inValue = new SIN.FacturacionServiciosBasicos.verificarComunicacion();
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionFacturaResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.recepcionFacturaAsync(SIN.FacturacionServiciosBasicos.recepcionFactura request)
        {
            return base.Channel.recepcionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionFacturaResponse> recepcionFacturaAsync(SIN.FacturacionServiciosBasicos.solicitudRecepcionFactura SolicitudServicioRecepcionFactura)
        {
            SIN.FacturacionServiciosBasicos.recepcionFactura inValue = new SIN.FacturacionServiciosBasicos.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).recepcionFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.validacionRecepcionMasivaFacturaResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.validacionRecepcionMasivaFacturaAsync(SIN.FacturacionServiciosBasicos.validacionRecepcionMasivaFactura request)
        {
            return base.Channel.validacionRecepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(SIN.FacturacionServiciosBasicos.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva)
        {
            SIN.FacturacionServiciosBasicos.validacionRecepcionMasivaFactura inValue = new SIN.FacturacionServiciosBasicos.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).validacionRecepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionMasivaFacturaResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.recepcionMasivaFacturaAsync(SIN.FacturacionServiciosBasicos.recepcionMasivaFactura request)
        {
            return base.Channel.recepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(SIN.FacturacionServiciosBasicos.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva)
        {
            SIN.FacturacionServiciosBasicos.recepcionMasivaFactura inValue = new SIN.FacturacionServiciosBasicos.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).recepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.verificacionEstadoFacturaResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.verificacionEstadoFacturaAsync(SIN.FacturacionServiciosBasicos.verificacionEstadoFactura request)
        {
            return base.Channel.verificacionEstadoFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(SIN.FacturacionServiciosBasicos.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura)
        {
            SIN.FacturacionServiciosBasicos.verificacionEstadoFactura inValue = new SIN.FacturacionServiciosBasicos.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).verificacionEstadoFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.validacionRecepcionPaqueteFacturaResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.validacionRecepcionPaqueteFacturaAsync(SIN.FacturacionServiciosBasicos.validacionRecepcionPaqueteFactura request)
        {
            return base.Channel.validacionRecepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(SIN.FacturacionServiciosBasicos.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete)
        {
            SIN.FacturacionServiciosBasicos.validacionRecepcionPaqueteFactura inValue = new SIN.FacturacionServiciosBasicos.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).validacionRecepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.anulacionFacturaResponse> SIN.FacturacionServiciosBasicos.ServicioFacturacion.anulacionFacturaAsync(SIN.FacturacionServiciosBasicos.anulacionFactura request)
        {
            return base.Channel.anulacionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.FacturacionServiciosBasicos.anulacionFacturaResponse> anulacionFacturaAsync(SIN.FacturacionServiciosBasicos.solicitudAnulacion SolicitudServicioAnulacionFactura)
        {
            SIN.FacturacionServiciosBasicos.anulacionFactura inValue = new SIN.FacturacionServiciosBasicos.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            return ((SIN.FacturacionServiciosBasicos.ServicioFacturacion)(this)).anulacionFacturaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pilotosiatservicios.impuestos.gob.bo/v2/ServicioFacturacionServicioBasico" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturacionClient.GetBindingForEndpoint(EndpointConfiguration.ServicioFacturacionPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturacionClient.GetEndpointAddress(EndpointConfiguration.ServicioFacturacionPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioFacturacionPort,
        }
    }
}
